version: '3.7'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pdf_django
      - POSTGRES_PASSWORD=pdf_django
      - POSTGRES_DB=pdf_django_dev
  redis:
    image: redis:alpine
  celery:
      build: ./
      command: celery -A pdf_django worker -l info
      volumes:
        - ./:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      depends_on:
        - redis
  celery-beat:
      build: ./
      command: celery -A pdf_django beat -l info
      volumes:
        - ./:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      depends_on:
        - redis
volumes:
  postgres_data:
